#!/bin/bash

#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !MODULE: make_runscripts
#
# !DESCRIPTION: Creates run scripts for a 1-year benchmark simulation
#\\
#\\
# !CALLING SEQUENCE:
#  make_runscripts VERSION START-YEAR [NUMBER-OF-RUNS]
#
# !REVISION HISTORY: 
#  03 Mar 2016 - M. Sulprizio- Initial version
#EOP
#------------------------------------------------------------------------------
#BOC

# Template run script
infile="run.template"

if [[ $# == 4 ]]; then
   version=$1
   year1=$2
   month1=$3
   nruns=$4
elif [[ $# == 3 ]]; then
   version=$1
   year1=$2
   month1=$3
   nruns=24
else
   echo "Usage: make_runscripts VERSION START-YEAR START-MONTH [NUMBER-OF-RUNS]"
   exit 1
fi

Floor () {
  DIVIDEND=${1}
  DIVISOR=${2}
  RESULT=$(( ( ${DIVIDEND} - ( ${DIVIDEND} % ${DIVISOR}) )/${DIVISOR} ))
  echo ${RESULT}
}

echo "Creating $nruns run scripts from $infile"

if [ -f $infile ]; then

   for i in $(seq 1 $nruns); do

      # Define run string
      if [ $i -ge 10 ]; then
         RUN=$i
      else
	 RUN="0"$i
      fi

      # Set dates
      MONTH=$((month1 + i - 1))

      if [ $MONTH -gt 12 ]; then
	 if (( $MONTH % 12 == 0 )); then
            NYEAR=$(expr $MONTH / 12 - 1 )
         else
	    NYEAR=$( Floor $MONTH 12 )
	 fi
	 YEAR=$((year1 + NYEAR))
	 MONTH=$((MONTH - (12 * NYEAR)))
      else
	 YEAR=$year1
      fi

      if [ $MONTH -ge 10 ]; then
         DATE1="${YEAR}${MONTH}"
      else
         DATE1="${YEAR}0${MONTH}"
      fi
      #echo $DATE1

      # Replace run number in run script
      sed -e "s/{CDATE}/$DATE1/ig" -e "s/{VERSTR}/$version/ig" -e "s/{STYEAR}/$YEAR/ig" -e "s/{STMONTH}/$MONTH/ig" $infile > run.tmp
      echo " -- $version.$DATE1"
      mv run.tmp $version.$DATE1

   done

   # Make scripts executable
   chmod 755 $version.*

else
   echo "Could not find input file: $INP"
   exit 1
fi

# Exit normally
exit 0

#EOC
