#!/bin/bash
#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !MODULE: pack_1yr_run
#
# !DESCRIPTION: Compressed the 1-year benchmark run directory so that it can
#  be copied to the permanent ftp site.
#\\
#\\
# !CALLING SEQUENCE:
#  ./pack_1yr_run
#
# !REMARKS:
#  Do not compress the output directory. These files need to be accessible
#  to allow developers to examine benchmark plots on the ftp site.
#
# !REVISION HISTORY: 
#  23 Mar 2015 - M. Sulprizio- Initial version
#EOP
#------------------------------------------------------------------------------
#BOC
 
# Remove files and directories that don't need to be archived
#unlink CodeDir
#unlink runScriptSamples
#rm -rf build
#rm -fv gcclassic
#rm -fv download_data*
#rm -fv *.py
#rm -fv *.sh

echo "==========================================================="
echo "Compressing Logs"
mv build_info/* Logs/
rmdir build_info
tar zcvf Logs.tar.gz Logs
#rm -rfv Logs

echo "==========================================================="
echo "Compressing OutputDir"
tar zcvf OutputDir.tar.gz OutputDir
#rm -rfv Outputdir

echo "==========================================================="
echo "Compressing Restarts"
tar zcvf Restarts.tar.gz Restarts
#rm -rfv Restarts

echo "==========================================================="
echo "Moving config files to Config/"
mv -v *.rc* ./Config/
mv -v *.yml ./Config/
echo "Compressing Config"
tar zcvf Config.tar.gz Config
#rm -rfv Config

echo "==========================================================="
echo "Moving files to RunScripts"
mv -v *.env ./RunScripts
mv -v getRunInfo ./RunScripts
echo "Compressing RunScripts"
tar zcvf RunScripts.tar.gz RunScripts
#rm -rfv RunScripts

echo "==========================================================="
echo "DONE COMPRESSING 1-YR BENCHMARK RUN DIRECTORY"
echo " "
echo "*** REMINDER ***"
echo " - Update README file to reflect version updates"
echo "==========================================================="

# Exit normally
exit 0
#EOC
