#!/bin/bash

#------------------------------------------------------------------------------
#          Harvard University Atmospheric Chemistry Modeling Group            !
#------------------------------------------------------------------------------
#BOP
#
# !MODULE: setup_1yr_run
#
# !DESCRIPTION: Sets up a run directory for a 1-year simulation
#\\
#\\
# !CALLING SEQUENCE:
#  ./setup_1yr_run
#
# !REVISION HISTORY: 
#  03 Aug 2017 - M. Sulprizio- Initial version
#EOP
#------------------------------------------------------------------------------
#BOC

#----------------------------------------------------------------
# Define version name
#----------------------------------------------------------------

BM_VERSION="GCC_14.2.0-rc.1"  # Benchmark long version name

START_YR=2018
START_MON=7
N_MONTHS=18

TEMP="temp.txt"

echo "==========================================================="
echo "CREATING 1-YR RUN DIRECTORY for $BM_VERSION"
echo "==========================================================="
echo ""

#----------------------------------------------------------------
# Create subdirectories
#----------------------------------------------------------------
mkdir -v Config            # For *.yml files
mkdir -v Logs              # For *.log files
mkdir -v RunScripts        # For run scripts  
mkdir -v BenchmarkResults  # For GCPy output

#----------------------------------------------------------------
# Remove unnecessary files
#----------------------------------------------------------------
rm -rf Restarts/GEOSChem.Restart.20190701_0000z.nc4
rm -rf geoschem.benchmark.run

#----------------------------------------------------------------
# Set up geoschem_config.yml files
#----------------------------------------------------------------
echo -e "Setting up geoschem_config.yml\n"
mv geoschem_config.yml Config/
cd Config

inFile="geoschem_config.yml.template"

# Need to replace the following text
OLD1="20190701"
NEW1="{DATE1}"

OLD2="20190801"
NEW2="{DATE2}"

cp geoschem_config.yml $inFile

# Replace text
echo -e "Replacing text in $inFile\n"
sed -i -e "s/$OLD1/$NEW1/g" "$inFile"
sed -i -e "s/$OLD2/$NEW2/g" "$inFile"

# Move back to top-level run directory
rm geoschem_config.yml
cd ..

#----------------------------------------------------------------
# Modify HEMCO_Config.rc to accept restart file for different year
#----------------------------------------------------------------
sed -i -e "s/EFYO/CYS/g" HEMCO_Config.rc

#----------------------------------------------------------------
# Set up HISTORY.rc
#----------------------------------------------------------------
echo -e "Setting up diagnostics in HISTORY.rc\n"

inFile="HISTORY.rc"

OLD3="#'DryDep',"
NEW3="'DryDep',"

OLD4="#'ProdLoss',"
NEW4="'ProdLoss',"

OLD5="#'WetLoss"
NEW5="'WetLoss"

OLD6="#'LevelEdgeDiags"
NEW6="'LevelEdgeDiags"

OLD7="#'ConcAfterChem"
NEW7="'ConcAfterChem"

OLD8="#'StateChm"
NEW8="'StateChm"

OLD9="#'CloudConvFlux"
NEW9="'CloudConvFlux"

# Replace text
echo -e "Replacing text in $inFile\n"
sed -i -e "s/$OLD3/$NEW3/g" "$inFile"
sed -i -e "s/$OLD4/$NEW4/g" "$inFile"
sed -i -e "s/$OLD5/$NEW5/g" "$inFile"
sed -i -e "s/$OLD6/$NEW6/g" "$inFile"
sed -i -e "s/$OLD7/$NEW7/g" "$inFile"
sed -i -e "s/$OLD8/$NEW8/g" "$inFile"
sed -i -e "s/$OLD9/$NEW9/g" "$inFile"

#----------------------------------------------------------------
# Set up run scripts
#----------------------------------------------------------------
echo -e "Setting up run scripts\n"
cp ~/GC/benchmarks/1yr/template_files/run.template RunScripts/
cp ~/GC/benchmarks/1yr/template_files/make_runscripts RunScripts/
cp ~/GC/benchmarks/1yr/template_files/job_depend.pl RunScripts/
cd RunScripts
./make_runscripts ${BM_VERSION} ${START_YR} ${START_MON} ${N_MONTHS}
cd ..

#----------------------------------------------------------------
# Copy other necessary files
#----------------------------------------------------------------
echo -e "Setting up run scripts\n"
cp ~/GC/benchmarks/1yr/template_files/pack_1yr_run .
cp ~/GC/benchmarks/1yr/template_files/copy_1yr_run .
cp ~/gcpy/benchmark/config/1yr_fullchem_benchmark.yml BenchmarkResults/

echo "==========================================================="
echo "DONE CREATING 1-YR RUN DIRECTORY"
echo " "
echo " Remember to copy GEOS-Chem restart file from the last"
echo " 1-year benchmark and to modify HISTORY.rc as needed "
echo "==========================================================="

# Exit normally
exit 0
#EOC
